In [ ]:
import numpy as np
import statistics as st
age = [12,15,21,21,18,19,25,30,30,28,29,40,12,18,25]
mean_result = np.mean(age)
print(mean_result)



22.866666666666667


In [ ]:
median_result = np.median(age)
print(median_result)

21.0


In [ ]:
import statistics as st
mode_result = st.mode(age)
print(mode_result)

12


In [ ]:
std_result = st.stdev(age)
print(std_result)

7.726269351714196


In [ ]:
var_result = st.variance(age)
print(var_result)

59.695238095238096


In [ ]:
height = [45, 67, 23, 67, 89, 34, 56, 67, 89, 12, 90, 45, 67, 34, 56, 78, 23, 45, 67, 89, 12]
var_result = st.variance(height)
print(var_result)

643.6


In [ ]:
std_result = st.stdev(height)
print(std_result)

25.369272752682527


In [ ]:
percentile_10th = np.percentile(height,10)
print(percentile_10th)

23.0


In [ ]:
percentile_25th = np.percentile(height,25)
print(percentile_25th)

34.0


In [ ]:
percentile_50th = np.percentile(height,50)
print(percentile_50th)

56.0


In [ ]:
percentile_75th = np.percentile(height,75)
print(percentile_75th)

67.0


In [ ]:
import numpy as np
matrix_a = np.array([[3,5,7],[2,4,6],[3,6,9], [9,8,12]])
print(matrix_a)

[[ 3  5  7]
 [ 2  4  6]
 [ 3  6  9]
 [ 9  8 12]]


In [ ]:
matrix_a.shape

(4, 3)

In [ ]:
matrix_b = np.array([[2,4,6],[3,7,2],[1,3,5],[8,1,4]])
print(matrix_b)

[[2 4 6]
 [3 7 2]
 [1 3 5]
 [8 1 4]]


In [ ]:
matrix_b.shape

(4, 3)

In [ ]:
addition = matrix_a + matrix_b
print(addition)

[[ 5  9 13]
 [ 5 11  8]
 [ 4  9 14]
 [17  9 16]]


In [ ]:
subtraction = matrix_a - matrix_b
print(subtraction)

[[ 1  1  1]
 [-1 -3  4]
 [ 2  3  4]
 [ 1  7  8]]


In [ ]:
multiplication = matrix_a + matrix_b
print(multiplication)

[[ 5  9 13]
 [ 5 11  8]
 [ 4  9 14]
 [17  9 16]]


In [ ]:
scalar = [-2]
print(scalar + matrix_a)

[[ 1  3  5]
 [ 0  2  4]
 [ 1  4  7]
 [ 7  6 10]]


In [ ]:
print(scalar * matrix_b)

[[ -4  -8 -12]
 [ -6 -14  -4]
 [ -2  -6 -10]
 [-16  -2  -8]]


In [ ]:
trans = np.transpose(matrix_a)
print(trans)

[[ 3  2  3  9]
 [ 5  4  6  8]
 [ 7  6  9 12]]


In [ ]:
tran.shape

(3, 4)

Checkpoint:
Create two matrices with 2 rows and 3 columns. Identify the type of matrix

In [ ]:
matrix_x = np.array([[2,5,8],[3,4,5]])
print(matrix_x)

[[2 5 8]
 [3 4 5]]


In [ ]:
matrix_x.shape

(2, 3)

In [ ]:
matrix_y = np.array([[3,2,4],[4,6,1]])
print(matrix_y)

[[3 2 4]
 [4 6 1]]


In [ ]:
matrix_y.shape

(2, 3)

Calculate the Mean, median and Mode of the matrices

In [ ]:
print(np.mean(matrix_x))

4.5


In [ ]:
print(np.mean(matrix_y))

3.3333333333333335


In [ ]:
print(np.median(matrix_x))

4.5


In [ ]:
print(np.median(matrix_y))

3.5


In [ ]:
from scipy import stats
mode = stats.mode(matrix_x)
print(mode)

ModeResult(mode=array([2, 4, 5]), count=array([1, 1, 1]))


In [ ]:
mode = stats.mode(matrix_y)
print(mode)

ModeResult(mode=array([3, 2, 1]), count=array([1, 1, 1]))


In [ ]:
flat_matrixX = matrix_x.flatten()
print(flat_matrixX)

[2 5 8 3 4 5]


In [ ]:
import statistics as st
mode = st.mode(flat_matrixX)
print(mode)

5


In [ ]:
flat_matrixY = matrix_y.flatten()
print(flat_matrixY)

[3 2 4 4 6 1]


In [ ]:
mode = st.mode(flat_matrixY)
print(mode)

4


Perform basic matrix operations (addition, subtraction, transpose and scalar multiplication) on the matrix.

Addition

In [ ]:
addition = matrix_x + matrix_y
print(addition)

[[ 5  7 12]
 [ 7 10  6]]


Subtraction

In [ ]:
subtraction = matrix_x + matrix_y
print(subtraction)

[[ 5  7 12]
 [ 7 10  6]]


Transpose

In [ ]:
trans = np.transpose(matrix_x)
print(trans)

[[2 3]
 [5 4]
 [8 5]]


In [ ]:
trans = np.transpose(matrix_y)
print(trans)

[[3 4]
 [2 6]
 [4 1]]


Scalar Multiplication

In [ ]:
scalar = [3]
print(scalar * matrix_x)


[[ 6 15 24]
 [ 9 12 15]]


In [ ]:
print(scalar * matrix_y)

[[ 9  6 12]
 [12 18  3]]


Real world application of Matrices and how they are used'

Matrices have numerous real-world applications across various fields, including:

1. Computer Graphics: Matrices are used to perform transformations, rotations, and scaling of objects in 2D and 3D space, creating realistic graphics and animations.

2. Data Analysis: Matrices are used in data mining, statistics, and machine learning to represent and manipulate large datasets, enabling data visualization, clustering, and prediction.

3. Cryptography: Matrices are used to develop secure encryption algorithms, like the Hill Cipher, to protect sensitive information.

4. Network Analysis: Matrices represent complex networks, like social networks, traffic patterns, and electrical circuits, helping analyze connectivity and optimize performance.

5. Physics and Engineering: Matrices describe linear systems, like electrical circuits, mechanical systems, and quantum mechanics, facilitating calculations and simulations.

6. Image Processing: Matrices are used in image filtering, convolution, and transformation, enhancing image quality and extracting features.

7. Economics: Matrices model economic systems, helping analyze supply and demand, resource allocation, and economic growth.

8. Biology: Matrices represent population dynamics, chemical reactions, and biological networks, enabling simulations and predictions.

9. Navigation and Control: Matrices are used in GPS, robotics, and control systems to determine positions, velocities, and optimize control strategies.

10. Medical Imaging: Matrices reconstruct images from data in MRI and CT scans, helping diagnose and treat medical conditions.

